# Generated by Django 4.1.9 on 2023-05-28 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 28, 12, 20, 47, 522522, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 28, 12, 20, 47, 522540, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
